export const STORAGE_KEYS = {
  positions: '@ortrack:positions',
  hidePortfolioValue: '@ortrack:hide_portfolio_value',
  onboardingComplete: '@ortrack:onboarding_complete',
  biometricEnabled: '@ortrack:biometric_enabled',
  settings: '@ortrack:settings',
  spotCache: '@ortrack:spot_cache',
  priceHistory: '@ortrack:price_history',
  historyCachePrefix: '@ortrack:history_cache_',
  pushToken: '@ortrack:push_token',
  installTracked: '@ortrack:install_tracked',
  premiumNotify: '@ortrack:premium_notify',
  legacyPriceAlerts: '@ortrack:price_alerts',
  profil: '@ortrack:profil',
  launchPremium: '@ortrack:launch_premium',
} as const;
