export const STORAGE_KEYS = {
  positions: '@ortrack:positions',
  hidePortfolioValue: '@ortrack:hide_portfolio_value',
  onboardingComplete: '@ortrack:onboarding_complete',
  biometricEnabled: '@ortrack:biometric_enabled',
  settings: '@ortrack:settings',
  spotCache: '@ortrack:spot_cache',
  priceHistory: '@ortrack:price_history',
  historyCachePrefix: '@ortrack:history_cache_',
  notificationToken: '@ortrack:push_token',
  installTracked: '@ortrack:install_tracked',
  premiumNotify: '@ortrack:premium_notify',
  legacyPriceAlerts: '@ortrack:price_alerts',
  profil: '@ortrack:profil',
  launchPremium: '@ortrack:launch_premium',
  privacyMode: '@ortrack_privacy_mode',
} as const;

export const WIPE_STORAGE_KEYS = [
  STORAGE_KEYS.positions,
  STORAGE_KEYS.hidePortfolioValue,
  STORAGE_KEYS.privacyMode,
  STORAGE_KEYS.onboardingComplete,
  STORAGE_KEYS.biometricEnabled,
  STORAGE_KEYS.settings,
  STORAGE_KEYS.spotCache,
  STORAGE_KEYS.priceHistory,
  STORAGE_KEYS.historyCachePrefix,
  STORAGE_KEYS.notificationToken,
  STORAGE_KEYS.installTracked,
  STORAGE_KEYS.premiumNotify,
  STORAGE_KEYS.legacyPriceAlerts,
  STORAGE_KEYS.profil,
  STORAGE_KEYS.launchPremium,
] as const;
